spring: 
    profiles: 
        active: 
        - dev
---
spring: 
    profiles: dev
    application: 
          name: microservicecloud-config-htah-dev
---
spring: 
    profiles: dev
    application: 
          name: microservicecloud-config-htah-test